// About
export const CREATE_ABOUT = "CREATE_ABOUT";
export const CREATE_ABOUT_RED = "CREATE_ABOUT_RED";
export const GET_ABOUT = "GET_ABOUT";
export const GET_ABOUT_RED = "GET_ABOUT_RED";
export const UPDATE_ABOUT = "UPDATE_ABOUT";
export const UPDATE_ABOUT_RED = "UPDATE_ABOUT_RED";
export const DELETE_ABOUT = "DELETE_ABOUT";
export const DELETE_ABOUT_RED = "DELETE_ABOUT_RED";

// Project
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_RED = "CREATE_PROJECT_RED";
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_RED = "GET_PROJECT_RED";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_RED = "UPDATE_PROJECT_RED";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_RED = "DELETE_PROJECT_RED";

// Campaign
export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
export const CREATE_CAMPAIGN_RED = "CREATE_CAMPAIGN_RED";
export const GET_CAMPAIGN = "GET_CAMPAIGN";
export const GET_CAMPAIGN_RED = "GET_CAMPAIGN_RED";
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const UPDATE_CAMPAIGN_RED = "UPDATE_CAMPAIGN_RED";
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_RED = "DELETE_CAMPAIGN_RED";

// Donation
export const CREATE_DONATION = "CREATE_DONATION";
export const CREATE_DONATION_RED = "CREATE_DONATION_RED";
export const GET_DONATION = "GET_DONATION";
export const GET_DONATION_RED = "GET_DONATION_RED";
export const UPDATE_DONATION = "UPDATE_DONATION";
export const UPDATE_DONATION_RED = "UPDATE_DONATION_RED";
export const DELETE_DONATION = "DELETE_DONATION";
export const DELETE_DONATION_RED = "DELETE_DONATION_RED";

// Volunteer
export const CREATE_VOLUNTEER = "CREATE_VOLUNTEER";
export const CREATE_VOLUNTEER_RED = "CREATE_VOLUNTEER_RED";
export const GET_VOLUNTEER = "GET_VOLUNTEER";
export const GET_VOLUNTEER_RED = "GET_VOLUNTEER_RED";
export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";
export const UPDATE_VOLUNTEER_RED = "UPDATE_VOLUNTEER_RED";
export const DELETE_VOLUNTEER = "DELETE_VOLUNTEER";
export const DELETE_VOLUNTEER_RED = "DELETE_VOLUNTEER_RED";

// Event
export const CREATE_EVENT = "CREATE_EVENT";
export const CREATE_EVENT_RED = "CREATE_EVENT_RED";
export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_RED = "GET_EVENT_RED";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPDATE_EVENT_RED = "UPDATE_EVENT_RED";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_RED = "DELETE_EVENT_RED";

// Team Member
export const CREATE_TEAM_MEMBER = "CREATE_TEAM_MEMBER";
export const CREATE_TEAM_MEMBER_RED = "CREATE_TEAM_MEMBER_RED";
export const GET_TEAM_MEMBER = "GET_TEAM_MEMBER";
export const GET_TEAM_MEMBER_RED = "GET_TEAM_MEMBER_RED";
export const UPDATE_TEAM_MEMBER = "UPDATE_TEAM_MEMBER";
export const UPDATE_TEAM_MEMBER_RED = "UPDATE_TEAM_MEMBER_RED";
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER";
export const DELETE_TEAM_MEMBER_RED = "DELETE_TEAM_MEMBER_RED";

// Partner
export const CREATE_PARTNER = "CREATE_PARTNER";
export const CREATE_PARTNER_RED = "CREATE_PARTNER_RED";
export const GET_PARTNER = "GET_PARTNER";
export const GET_PARTNER_RED = "GET_PARTNER_RED";
export const UPDATE_PARTNER = "UPDATE_PARTNER";
export const UPDATE_PARTNER_RED = "UPDATE_PARTNER_RED";
export const DELETE_PARTNER = "DELETE_PARTNER";
export const DELETE_PARTNER_RED = "DELETE_PARTNER_RED";

// Blog
export const CREATE_BLOG = "CREATE_BLOG";
export const CREATE_BLOG_RED = "CREATE_BLOG_RED";
export const GET_BLOG = "GET_BLOG";
export const GET_BLOG_RED = "GET_BLOG_RED";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const UPDATE_BLOG_RED = "UPDATE_BLOG_RED";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_BLOG_RED = "DELETE_BLOG_RED";

// Testimonial
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

// Gallery
export const CREATE_GALLERY = "CREATE_GALLERY";
export const CREATE_GALLERY_RED = "CREATE_GALLERY_RED";
export const GET_GALLERY = "GET_GALLERY";
export const GET_GALLERY_RED = "GET_GALLERY_RED";
export const UPDATE_GALLERY = "UPDATE_GALLERY";
export const UPDATE_GALLERY_RED = "UPDATE_GALLERY_RED";
export const DELETE_GALLERY = "DELETE_GALLERY";
export const DELETE_GALLERY_RED = "DELETE_GALLERY_RED";

// Impact
export const CREATE_IMPACT = "CREATE_IMPACT";
export const CREATE_IMPACT_RED = "CREATE_IMPACT_RED";
export const GET_IMPACT = "GET_IMPACT";
export const GET_IMPACT_RED = "GET_IMPACT_RED";
export const UPDATE_IMPACT = "UPDATE_IMPACT";
export const UPDATE_IMPACT_RED = "UPDATE_IMPACT_RED";
export const DELETE_IMPACT = "DELETE_IMPACT";
export const DELETE_IMPACT_RED = "DELETE_IMPACT_RED";

// FAQ
export const CREATE_FAQ = "CREATE_FAQ";
export const CREATE_FAQ_RED = "CREATE_FAQ_RED";
export const GET_FAQ = "GET_FAQ";
export const GET_FAQ_RED = "GET_FAQ_RED";
export const UPDATE_FAQ = "UPDATE_FAQ";
export const UPDATE_FAQ_RED = "UPDATE_FAQ_RED";
export const DELETE_FAQ = "DELETE_FAQ";
export const DELETE_FAQ_RED = "DELETE_FAQ_RED";

// Contact Us / Contact Message
export const CREATE_CONTACT_US = "CREATE_CONTACT_US";
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED";
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US";
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED";
export const DELETE_CONTACT_US = "DELETE_CONTACT_US";
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED";

// User
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_RED = "CREATE_USER_RED";
export const GET_USER = "GET_USER";
export const GET_USER_RED = "GET_USER_RED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_RED = "UPDATE_USER_RED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RED = "DELETE_USER_RED";
